// ============================================================================
// AUTO-GENERATED by scripts/gen-db-init-sql.mjs — do not edit by hand.
// Idempotent Postgres DDL (IF NOT EXISTS) mirroring prisma/schema.prisma (PostgreSQL default)
// (source migration: prisma/migrations/20260910000000_init/migration.sql).
// Used by src/lib/db-bootstrap.ts to self-provision tables at runtime when the
// build-time "prisma db push" did not run (e.g. default `next build` on Vercel).
// If you change the Prisma schema, regenerate: node scripts/gen-db-init-sql.mjs
// ============================================================================

export const DB_INIT_SQL = `
-- CreateSchema
CREATE SCHEMA IF NOT EXISTS "public";

-- CreateTable
CREATE TABLE IF NOT EXISTS "patients" (
    "patient_id" TEXT NOT NULL,
    "first_name" TEXT NOT NULL,
    "last_name" TEXT NOT NULL,
    "date_of_birth" TIMESTAMP(3) NOT NULL,
    "sex" TEXT NOT NULL,
    "phone_number" TEXT NOT NULL,
    "email" TEXT,
    "address_line_1" TEXT NOT NULL,
    "address_line_2" TEXT,
    "city" TEXT NOT NULL,
    "state" TEXT NOT NULL,
    "zip_code" TEXT NOT NULL,
    "insurance_provider" TEXT,
    "insurance_member_id" TEXT,
    "preferred_language" TEXT NOT NULL DEFAULT 'English',
    "emergency_contact_name" TEXT,
    "emergency_contact_phone" TEXT,
    "created_at" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updated_at" TIMESTAMP(3) NOT NULL,
    "deleted_at" TIMESTAMP(3),

    CONSTRAINT "patients_pkey" PRIMARY KEY ("patient_id")
);

-- CreateTable
CREATE TABLE IF NOT EXISTS "call_sessions" (
    "id" TEXT NOT NULL,
    "session_id" TEXT NOT NULL,
    "channel" TEXT NOT NULL DEFAULT 'web',
    "caller_number" TEXT,
    "language" TEXT NOT NULL DEFAULT 'en',
    "status" TEXT NOT NULL DEFAULT 'in_progress',
    "outcome" TEXT,
    "transcript" TEXT NOT NULL DEFAULT '[]',
    "collected_data" TEXT,
    "patient_id" TEXT,
    "error_message" TEXT,
    "started_at" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "ended_at" TIMESTAMP(3),

    CONSTRAINT "call_sessions_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE IF NOT EXISTS "appointments" (
    "id" TEXT NOT NULL,
    "patient_id" TEXT NOT NULL,
    "appointment_date" TIMESTAMP(3) NOT NULL,
    "provider" TEXT NOT NULL,
    "reason" TEXT,
    "status" TEXT NOT NULL DEFAULT 'scheduled',
    "created_at" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "appointments_pkey" PRIMARY KEY ("id")
);

-- CreateIndex
CREATE INDEX IF NOT EXISTS "patients_phone_number_idx" ON "patients"("phone_number");

-- CreateIndex
CREATE INDEX IF NOT EXISTS "patients_last_name_idx" ON "patients"("last_name");

-- CreateIndex
CREATE INDEX IF NOT EXISTS "patients_date_of_birth_idx" ON "patients"("date_of_birth");

-- CreateIndex
CREATE UNIQUE INDEX IF NOT EXISTS "call_sessions_session_id_key" ON "call_sessions"("session_id");

-- CreateIndex
CREATE INDEX IF NOT EXISTS "call_sessions_started_at_idx" ON "call_sessions"("started_at");

-- CreateIndex
CREATE INDEX IF NOT EXISTS "call_sessions_patient_id_idx" ON "call_sessions"("patient_id");

-- CreateIndex
CREATE INDEX IF NOT EXISTS "appointments_patient_id_idx" ON "appointments"("patient_id");

-- CreateIndex
CREATE INDEX IF NOT EXISTS "appointments_appointment_date_idx" ON "appointments"("appointment_date");

-- AddForeignKey
ALTER TABLE "appointments" ADD CONSTRAINT "appointments_patient_id_fkey" FOREIGN KEY ("patient_id") REFERENCES "patients"("patient_id") ON DELETE RESTRICT ON UPDATE CASCADE;`;
